name: "Other"
description: "Not a bug, nor a feature request"
body:
  - type: "textarea"
    attributes:
      label: "What's on your mind?"
      description: "Feel free to talk about whatever."
    validations:
      required: false
